### ISSUE TITLE
大佬麻烦您看一下给个回复好吗，

### ISSUE THREAD

**Issue by wyzGitHub** [AiziChen/auto-answer-server#1]
我想搭建CNS服务网上教程都引用的您的[CNS仓库](https://github.com/AiziChen/CNS/releases/tag/0.2.3r2)
**我去访问已经404了**麻烦您看一下**您有备份吗**
可以**麻烦您给我发邮箱一份吗**
谢谢

**Comment by AiziChen** [comment]
已重新公开CNS仓库。记得fork到自己的仓库，以免在以后会再次看不见。
